spring:
  application:
    name : firstproject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hee?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234

  mail:
    host: smtp.example.com
    port: 587
    username: beauty1746@gmail.com
    password: yrclove1746!


    jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
      format_sql: true
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always


